export const TRAER_BADGES = "traer_badges" 
export const ENCONTRAR_BADGES = "encontrar_badges"
export const DELETE_BADGES = "delete_badges" 
export const ERROR = "error_badges" 
export const CARGANDO = "cargando_badges" 